name: check_vpn_connection
description: A simple and lightweight Flutter package that lets you define VPN connection status on your devices.
version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: